### PR TITLE
refactor: compiler and dependencies

### PR DESCRIPTION
**Pull request by MatteoGabriele**
Unrelated to the issue I have recently opened, this PR focuses more on the compiler side. 

While I was playing with the code, I saw many outdated dev dependencies, two different compilers, and 78% of the bundle it's taken by core-js modules, and I'm not sure the reason behind the last one. 
[Here](https://bundlephobia.com/result?p=vue-element-query@3.0.1) you can see how the package is broken down.

I also added:
- A minified version.
- Unpkg and jsdelivr properties in package.json.
- I moved Vue as a peer-dependency.
- Removed polyfills as a dependency. 
Technically we would not even need the resize-observer-polyfill package because the [API](https://developer.mozilla.org/en-US/docs/Web/API/Resize_Observer_API) is available natively in all major browsers except IE. Still, I guess you could leave it as is or add it as an optional dependency.

Please feel free to discard everything if you don't feel like it or don't like it or just use it as a reference if you want to.

Thanks again

### CODE REVIEW

**Comment by e2o** [comment]
If it works, it works 😅  a bit risky touching deps here that are 2-3 years old. 

The core-js modules are added by babel to reach the required browser support defined here:
https://github.com/e2o/vue-element-query/blob/master/.babelrc

As for the changes;
Your remarks are mostly justified. I'll see if I can find some time in the future to do the following:
- Update deps where possible
- I would rather stay with `rollup` if possible.
- Add a minified build of the plugin.
- The ResizeObserver right now is used in the form of a [ponyfill](https://github.com/sindresorhus/ponyfill), it's only taking up minimal space in the bundle, so I would leave it as is.
- remove webpack and the `example/`-folder (that's why there is both `webpack` and `rollup`), then Vue can indeed be moved to peer-deps.

I will assign you as a reviewer when I'm done with this. Thanks for the kickstart on this.

**Comment by MatteoGabriele** [comment]
I get the hesitation, but the package would go from ~25.9kb to ~1.33kb (minified + gzipped).
`bili` it's a compiler that uses rollup under the hood. I've been using it for all my open-source projects, and it removes a lot of the stress of making a compiler all the time.

thanks again for your time

**Comment by MatteoGabriele** [comment]
This could easily be a major bump to v4

**Comment by MatteoGabriele** [comment]
We could do this in a better way. Maybe we can also refresh the compiler if you decide to go for vue3. I'll close this for now

**Pull request closed without merging**
